
theme: agency-jekyll-theme

url: http://www.gfru.it

# Site settings
title: Grapefruit Trading
email: crypto@gfru.it
description: "A leader in grapefruits"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/GrapefruitTrade

# Postal address (add as many lines as necessary)
address:
  - line: 10 E Ohio St
  - line: Chicago, IL 60611

# Build settings
markdown: kramdown
permalink: pretty

include: [_redirects]